markjs_search.profile.*:
  type: config_entity
  label: MarkJS profile
  mapping:
    id:
      type: string
      label: MarkJS profile identifier
    label:
      type: string
      label: MarkJS profile label
    element:
      type: string
      label: MarkJS profile element
    class_name:
      type: string
      label: MarkJS profile element class name
    exclude:
      type: string
      label: The MarkJS exclude
    separate_word_search:
      type: boolean
      label: MarkJS separate word search
    diacritics:
      type: boolean
      label: MarkJS diacritics
    wildcard:
      type: string
      label: MarkJS wildcard
    accuracy:
      type: string
      label: MarkJS accuacy level
    synonyms:
      type: text
      label: MarkJS synonyms JSON object
    iframes:
      type: boolean
      label: MarkJS iframes search
    iframes_timeout:
      type: integer
      label: MarkJS iframes timeout
    case_sensitive:
      type: boolean
      label: MarkJS case sensitive
    across_elements:
      type: boolean
      label: MarkJS across elements
    ignore_joiners:
      type: boolean
      label: MarkJS ignore joiners
    ignore_punctuation:
      type: string
      label: MarkJS ignore punctuation
    callbacks:
      type: mapping
      label: MarkJS callback funcitons
      mapping:
        each:
          type: string
          label: Each callback function
        filter:
          type: string
          label: Filter callback function
        done:
          type: string
          label: Done callback function
        no_match:
          type: string
          label: No match callback function
    debug:
      type: boolean
      label: MarkJS enable debug
    log:
      type: string
      label: MarkJS log object
